# Generated by Django 2.2.6 on 2019-10-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurios', '0003_auto_20191021_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinosaurio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='dinos', verbose_name='Imagen'),
        ),
    ]
