# Generated by Django 2.2.7 on 2019-11-20 19:31

import dinosaurios.validador
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurios', '0004_auto_20191028_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinosaurio',
            name='altura',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[dinosaurios.validador.validar_altura]),
        ),
        migrations.AlterField(
            model_name='dinosaurio',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100, 'Error en la longutud')]),
        ),
    ]
